language: java

addons:
  sonarcloud:
    organization: "wbenica-github"
    token:
      secure: "52278beb9c6c6daef443bd3352cc3ea3d5bbfbb7"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar